### ISSUE TITLE
Define Architecture

### ISSUE THREAD

**Issue by dalagnol** [dalagnol/feathery-frontend#1]
Any good project needs a good architecture to stick by. In this task, we’ll discuss the pros and cons of available technologies for us to use and pick which ones we’ll be sticking by in the development of Feathery.

### Dialect Definition
- [x] Choose between TypeScript or JavaScript: **TypeScript**
- [x] Define file extensions: **.ts for normal files, .tsx if file has JSX in it**

### Store Definition
- [x] MobX or Redux: **Redux**

### Tests
- [x] Tutorial about tests
- [x] Jest

### Structure of Project
- [x] File Structure
- [x] Strict separation of responsibilities and concerns

- Every importable directory will be indexed
- Collocation principle (component to component, view to view)
- Use of Services

### React
- [x] Class or Functional components: Functional, obviously

### Globalisation
- [x] Multilanguage project: yes

### Styling
- [x] Sass or Styled Components: styled-components

### REST Definitions
- [x] Backend routing review: fixed routes and services to attend the REST standard
- [x] Define routing system

### Component Structuring
- [x] Explain the Collocation principle
- [x] Views/Pages setup and definition of their rules: no master views, extensive App component
- [x] Define the purpose of the App Component: extensive hosting of master components

### Services Structuring
- [x] Explain philosophy behind Services

**Comment by morezco** [comment]
All done here
