### ISSUE TITLE
Define design constants

### ISSUE THREAD

**Issue by morezco** [dalagnol/feathery-frontend#18]
The website does not know screen sizes out of the box. We shall define the sizes to be served for Mobiles, Tablets and Desktops, and then store them in a constants file to be referenced across the project.

- [x] Define file format (CSS constant or TypeScript export?)
- [x] Create the file somewhere

Define the size limits for:
- [x] Mobile: @media (min-width: 30.0625em) and (max-width: 64em)
- [x] Tablet: @media (min-width: 64.0625em) and (max-width: 80em)
- [x] Desktop: @media (min-width: 80.0625em)

**Comment by dalagnol** [comment]
The size limits that were chosen follow the following pattern:

Desktop:
@media (min-width: 80.0625em)

Tablet:
@media (min-width: 64.0625em) and (max-width: 80em)

Mobile:
@media (min-width: 30.0625em) and (max-width: 64em)

The reason why em was the chosen unit of measurement is that for media queries it better affords browser zooming and it has a more consistent performance across different browsers. For a more detailed explanation, give the following articles a read:

- https://engageinteractive.co.uk/blog/em-vs-rem-vs-px

- https://zellwk.com/blog/media-query-units/

**Comment by morezco** [comment]
Okay. I for one remain doubtful on the numbers, however. We'll see how their implementation goes.

**Comment by dalagnol** [comment]
About the numbers, you can see in these screenshoots how each one of the media queries would behave.
![Screen Shot 2020-01-06 at 11 39 14 AM](https://user-images.githubusercontent.com/49122688/71826129-066b6180-307c-11ea-861a-9c5c88bd7e32.png)
![Screen Shot 2020-01-06 at 11 39 40 AM](https://user-images.githubusercontent.com/49122688/71826130-0703f800-307c-11ea-899a-a960928d8c1a.png)
![Screen Shot 2020-01-06 at 11 39 52 AM](https://user-images.githubusercontent.com/49122688/71826131-0703f800-307c-11ea-8320-684f6a45e403.png)

**Comment by morezco** [comment]
I have created a Screens file in the styles directory, exporting three functions that wrap arbitrary CSS into the relevant code for screen-sensitiveness. Creating the pull request soon and thus closing this.
